"""CPPython managed base ConanFile.

This file is auto-generated by CPPython. Do not edit manually.
Dependencies are managed through pyproject.toml.
"""

from conan import ConanFile


class CPPythonBase(ConanFile):
    """Base ConanFile with CPPython managed dependencies."""

    def requirements(self):
        """CPPython managed requirements."""
        self.requires("honesty/[>=0.0.0.dev1]")
        self.requires("synodic-template-library/[>=0.0.0.dev1]")
        self.requires("cppaste/[>=0.0.0.dev1]")
        self.requires("portability/[>=0.0.0.dev1]")
        self.requires("sdl/[>=3.2.20]")

    def build_requirements(self):
        """CPPython managed build and test requirements."""
        pass  # No test requirements
