[project]
description = "Profiling, testing, and benchmarking"
name = "soul-engine"

license = { text = "MIT" }

authors = [{ name = "Synodic Software", email = "contact@synodic.software" }]

readme = "README.md"

dynamic = ["version"]

dependencies = []
requires-python = ">=3.14"

[project.urls]
homepage = "https://github.com/synodic/Soul-Engine"
repository = "https://github.com/synodic/Soul-Engine"

[project.optional-dependencies]
build = ["cppython[cmake,conan,git]>=0.9.11"]
[dependency-groups]
lint = ["ruff>=0.14.5", "pyrefly>=0.42.1", "isort>=7.0.0"]
test = ["pytest-cov>=7.0.0", "pytest-mock>=3.15.1"]

[tool.cppython]
dependencies = [
	'honesty>=0.0.0.dev1',
	'synodic-template-library>=0.0.0.dev1',
	'cppaste>=0.0.0.dev1',
	'portability>=0.0.0.dev1',
	'sdl>=3.2.20',
]

[tool.cppython.generators.cmake]
preset_file = "tool/cmake/platform/common/CMakePresets.json"
configuration_name = "default"
cmake_binary = "C:/Program Files/CMake/bin/cmake.exe"

[tool.cppython.providers.conan]
remotes = []
skip_upload = true

[tool.pytest.ini_options]
log_cli = true
testpaths = ["tests"]

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120
preview = true

[tool.ruff.lint]
ignore = ["D206", "D300", "D415", "E111", "E114", "E117"]
select = [
	"D",   # pydocstyle
	"F",   # Pyflakes
	"I",   # isort
	"PL",  # pylint
	"UP",  # pyupgrade
	"E",   # pycodestyle
	"B",   # flake8-bugbear
	"SIM", # flake8-simplify
	"PT",  # flake8-pytest-style
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "single"

[tool.coverage.report]
skip_empty = true

[tool.pdm.scripts]
build = { shell = "cppython build" }
test = { shell = "cppython test" }

[build-system]
build-backend = "pdm.backend"
requires = ["pdm.backend"]
